### ISSUE TITLE
3rd Milestone Release Roadmap

### ISSUE THREAD

**Issue by elderanakain** [elderanakain/pa165-formula-one-team#64]
Source: https://is.muni.cz/auth/el/1433/podzim2018/PA165/seminars.qwarp?prejit=3982071

**User interface:**
- [x] Use Maven Cargo plugin with a recent version of Tomcat.
- [x] The web application must be available on the following HTTP context http://localhost:8080/pa165.
- [x] Your application should use an in-memory database.
- [x] Implement the user interface using Spring MVC, AngularJS, Angular, React or Vue.js.
- [ ] The user interface should allow to carry out all business functions of your system.
- [x] You should fill in all the necessary data automatically. So, for example, you can use Web Listener to load data during Web Application startup.
- [ ] Make sure there are validations implemented on the user interface.
- [x] Your user interface should use either Facade layer or REST layer to access the system. Do not directly access the database and do not directly use the Service layer.
- [x] The web interface layer may reside in a separate maven module.
- [ ] Each member of the team must implement (mostly independently) part of user interface. Including controller and view.

**REST layer:**
- [x] Your application should have a basic REST interface.
- [x] At least one entity and operations on that entity must be exposed. This is mainly to demonstrate you can implement this, it’s not necessary to have all application functions accessible through this interface.
- [x] The REST must be accessible at http://localhost:8080/pa165/rest
- [x] It is not required to have the interface secured.
- [x] You should include a README file with instructions on how to test the REST interface (e.g. CURL commands for command line).

**Security:**
- [x] There should be at least 2 roles in the system (e.g. Administrator, User). Each role should have some differences in the user interface or in capabilities.
- [x] There should be login form (not HTTP Basic).
- [x] Registration is NOT required. You can prefill the users and their passwords in the database.
The password should not be saved in the database in open form.
